name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous workflow
      uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}
        
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew build

    - name: Sign apk
      uses: r0adkll/sign-android-release@v1
      id: signApk
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.STORE_FILE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    - name: Upload apk
      uses: actions/upload-artifact@v3.1.0
      with:
        name: "WeiJu2.apk"
        path: ${{ steps.signApk.outputs.signedReleaseFile }}
