name: Nightly Build

on: 
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  nightly_build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        id: signApk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.STORE_FILE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: nightly
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: avakar/tag-and-release@v1
        id: createRelease
        with:
          tag_name: nightly
          release_name: WeiJu2 nightly build
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload nightly build asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createRelease.outputs.upload_url }}
          asset_path: ${{ steps.signApk.outputs.signedReleaseFile }}
          asset_name: WeiJu2.apk
          asset_content_type: application/zip
      
      
